name = "2clbrcloudflarenw"
pages_build_output_dir = ".vercel/output/static"

# Tambahkan tanggal hari ini atau tanggal rilis fitur ini
compatibility_date = "2026-05-07"
compatibility_flags = [ "nodejs_compat" ]
